apiVersion: batch/v1
kind: Job
metadata:
  name: kf-smoke-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: runner
        image: <REGISTRY>/kubeflow-smoke-test:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATA_DIR
          value: /data
        volumeMounts:
        - name: ws
          mountPath: /data
      volumes:
      - name: ws
        persistentVolumeClaim:
          claimName: kf-smoke-pvc
